import Head from "next/head";
import Header from "@/Components/Header/Header";
import About from "@/Components/About/About";
import AboutUsSlider from "@/Components/AboutUsSlider/AboutUsSlider";
import Advertise from "@/Components/Advertise/Advertise";
import Services from "@/Components/Services/Services";
import Calling from "@/Components/Calling/Calling";
import Menu from "@/Components/Menu/Menu";
import Counter from "@/Components/Counter/Counter";
import Testimonial from "@/Components/Testimonial/Testimonial";
import OurTeam from "@/Components/OurTeam/OurTeam";
import ContactUs from "@/Components/ContactUs/ContactUs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <About />
      <AboutUsSlider />
      <Advertise />
      <Services />
      <Calling />
      <Menu />
      <Counter />
      <Testimonial />
      <OurTeam />
      <ContactUs />
    </>
  );
}
